registry:
  restart: always
  image: odoko/registry:2
  ports:
    - 443:443
  environment:
    DOCKER_HOSTNAME: ${DOCKER_HOSTNAME}
    EMAIL: ${EMAIL}
    USERNAME: ${USERNAME}
    PASSWORD: ${PASSWORD}
    REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/${DOCKER_HOSTNAME}/domain.crt
    REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/${DOCKER_HOSTNAME}/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /opt/docker-registry:/var/lib/registry
    - /etc/letsencrypt/:/etc/letsencrypt
    - /etc/docker/auth:/auth

letsencryt-cron:
  restart: always
  image: odoko/registry:2
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
  command:
    - cron

rancher:
  image: rancher/server
  ports:
    - 8080:8080

jenkins:
  image: odoko/jenkins:2.7.1-odoko01
  ports:
   - 8081:8080
  environment:
    JENKINS_OPTS:
    DOCKER_HOSTNAME: ${DOCKER_HOSTNAME}
    USERNAME: ${USERNAME}
    PASSWORD: ${PASSWORD}
    PLUGINS: git 
  volumes:
   - /jenkins:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock

auth-proxy:
  image: odoko/auth-proxy:1.0.1
  ports:
    - 80:80
  environment:
    JENKINS_HOSTNAME: ${JENKINS_HOSTNAME}
    JENKINS_PORT: 8081
    RANCHER_HOSTNAME: ${RANCHER_HOSTNAME}
    RANCHER_PORT: 8080


